'use strict';
// BREED videos in the dark racing-program look. Writes hype-video.html (10s) and demo-video.html (24s).
// Both are DOM pages driven by window.__seek(t) so hype-video.cjs / demo-video.cjs can render them frame by frame.
const fs = require('fs'); const path = require('path');
const silk = new Function(fs.readFileSync(path.join(__dirname, 'form', 'silks.js'), 'utf8') + ';return silk')();
const C = { red: '#c8102e', blk: '#1b1b1b', yel: '#e0a100', grn: '#0b7a1e', blu: '#1d3f8f' };
const NOISE = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='220'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3CfeColorMatrix values='0 0 0 0 .93 0 0 0 0 .9 0 0 0 0 .83 0 0 0 .05 0'/%3E%3C/filter%3E%3Crect width='220' height='220' filter='url(%23n)'/%3E%3C/svg%3E")`;
const CSS = `*{margin:0;padding:0;box-sizing:border-box}html,body{width:1280px;height:720px;overflow:hidden;background:#12110e;color:#ece5d3;font-family:'Newsreader',Georgia,serif;-webkit-font-smoothing:antialiased}
body{background:#12110e ${NOISE}}
.sc{position:absolute;inset:0;opacity:0;padding:54px 80px}
.d{font-family:'Big Shoulders Display',Impact,sans-serif;font-weight:900;text-transform:uppercase;line-height:.9}
.d7{font-family:'Big Shoulders Display',sans-serif;font-weight:700;text-transform:uppercase;letter-spacing:.02em}
.m{font-family:'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.14em;font-size:13px}
.mut{color:#8a8372}.sub{color:#c4bca8}.g{color:#2fd64a}.r{color:#ff6b57}
.blk{background:#00c805;color:#12110e;padding:0 .1em;display:inline-block;line-height:.98}
.logo i{font-style:normal;color:#2fd64a}
.hd{display:flex;justify-content:space-between;align-items:flex-end;border-bottom:4px double #d9d1bd;padding-bottom:10px;margin-bottom:26px}
.cap{position:absolute;left:80px;right:80px;bottom:44px;display:flex;justify-content:space-between;border-top:1px solid #d9d1bd;padding-top:12px}
.row{display:flex;align-items:center;gap:18px;border-bottom:1px solid #3a362c;padding:12px 4px}
.row .grow{flex:1;min-width:0}
.nm{font-family:'Big Shoulders Display',sans-serif;font-weight:700;text-transform:uppercase;font-size:26px;letter-spacing:.02em;line-height:1}
.it{font-style:italic;color:#8a8372;font-size:17px}
.num{font-family:'IBM Plex Mono',monospace;font-size:18px}
.pp{font-family:'Big Shoulders Display',sans-serif;font-weight:900;font-size:32px;width:34px}
.chip{display:inline-block;font-family:'IBM Plex Mono',monospace;font-size:13px;letter-spacing:.06em;padding:4px 10px;border:1px solid #3a362c;margin-right:8px}
.chip.hit{background:#2fd64a;color:#12110e;border-color:#2fd64a;font-weight:600}
.chip.bull{border-color:#2fd64a;color:#2fd64a}
.btn{display:inline-block;font-family:'Big Shoulders Display',sans-serif;font-weight:900;text-transform:uppercase;letter-spacing:.05em;font-size:22px;padding:10px 22px 8px;border:2px solid #ece5d3}
.btn.go{background:#00c805;border-color:#00c805;color:#12110e}
.box{border:1px solid #d9d1bd;border-top:5px solid #d9d1bd;background:#181611;padding:24px 28px}
.inp{background:#1c1a15;border:1px solid #ece5d3;padding:12px 16px;font-family:'IBM Plex Mono',monospace;font-size:20px;min-height:50px}
.seg{display:grid;grid-template-columns:1fr 1fr;border:2px solid #ece5d3}.seg div{font-family:'Big Shoulders Display',sans-serif;font-weight:700;text-transform:uppercase;letter-spacing:.05em;font-size:22px;padding:12px 8px 9px;text-align:center}
.ps{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:22px}.ps div{border-top:2px solid #d9d1bd;padding-top:8px}.ps span{display:block}.ps b{font-family:'IBM Plex Mono',monospace;font-size:24px;font-weight:600}
.tote{display:grid;grid-template-columns:repeat(5,1fr);background:#000;border:1px solid #3a362c;font-family:'IBM Plex Mono',monospace;color:#f6e27a;text-align:center}.tote>div{padding:14px 6px;border-right:1px solid #3a362d}.tote>div:last-child{border-right:0}.tote .l{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#a79f8a}.tote .v{font-size:30px;font-weight:600}
.sp{border:1px solid #3a362c;padding:14px 6px;text-align:center}.sp svg{margin:0 auto;display:block}
.stamp{display:inline-block;border:4px solid #2fd64a;color:#2fd64a;font-family:'Big Shoulders Display',sans-serif;font-weight:900;font-size:54px;padding:4px 18px 0;text-transform:uppercase;transform-origin:center}`;
const ENGINE = `const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),ease=k=>1-Math.pow(1-k,3);
window.__seek=function(t){document.querySelectorAll('.sc').forEach(s=>{const a=+s.dataset.a,b=+s.dataset.b,f=.3;const o=Math.min(clamp((t-a)/f,0,1),1-clamp((t-(b-f))/f,0,1));s.style.opacity=(s.dataset.last?clamp((t-a)/f,0,1):o).toFixed(3);s.style.visibility=o>0||s.dataset.last&&t>=a?'visible':'hidden';
  s.querySelectorAll('[data-in]').forEach(e=>{const k=ease(clamp((t-a-(+e.dataset.in))/.45,0,1));const out=e.dataset.out!=null&&t-a>=+e.dataset.out;e.style.opacity=out?0:k.toFixed(3);const mode=e.dataset.fx||'up';e.style.transform=mode==='stamp'?'rotate(-7deg) scale('+(2.2-1.2*k).toFixed(3)+')':mode==='none'?'none':'translateY('+((1-k)*18).toFixed(1)+'px)';if(out&&e.dataset.gone)e.style.display='none';else if(e.dataset.gone)e.style.display='';});
  s.querySelectorAll('[data-type]').forEach(e=>{const txt=e.dataset.type,k=clamp((t-a-(+e.dataset.at))/(+e.dataset.dur||1),0,1);e.textContent=txt.slice(0,Math.round(txt.length*k))+(k>0&&k<1?'|':'');});
  s.querySelectorAll('[data-count]').forEach(e=>{const [x,y,at,dur,pre,dec]=e.dataset.count.split(',');const k=ease(clamp((t-a-(+at))/(+dur),0,1));const v=(+x)+((+y)-(+x))*k;e.textContent=(pre||'')+v.toLocaleString('en-US',{minimumFractionDigits:+dec||0,maximumFractionDigits:+dec||0});});
  s.querySelectorAll('[data-on]').forEach(e=>{const on=t-a>=+e.dataset.on;e.style.background=on?'#ece5d3':'transparent';e.style.color=on?'#12110e':'#ece5d3';});
  s.querySelectorAll('[data-off]').forEach(e=>{const on=t-a<+e.dataset.off;e.style.background=on?'#ece5d3':'transparent';e.style.color=on?'#12110e':'#ece5d3';});
});return t};
window.__ready=document.fonts.ready.then(()=>{window.__seek(0);return true});
if(location.hash==='#play'){const t0=performance.now();setInterval(()=>window.__seek(((performance.now()-t0)/1000)%DUR),33)}`;
const page = (dur, body, extra) => `<!doctype html><html><head><meta charset="utf-8">
<link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@700;900&family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,600;1,6..72,400&family=IBM+Plex+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>${CSS}${extra||""}</style></head><body>${body}<script>const DUR=${dur};${ENGINE}</script></body></html>`;
const sc = (a, b, html, last) => `<div class="sc" data-a="${a}" data-b="${b}"${last ? ' data-last="1"' : ''}>${html}</div>`;
const logo = (px) => `<div class="d logo" style="font-size:${px}px;line-height:.8">BR<i>EE</i>D</div>`;
const hd = (label) => `<div class="hd">${logo(58)}<div class="m mut">${label}</div></div>`;
const cap = (l, r) => `<div class="cap m"><span class="g">${l}</span><span class="mut">${r}</span></div>`;
const BREEDS = [['Thoroughbred', 'Momentum. Longs the strongest five-minute mover.', C.red, '2x'], ['Mustang', 'Fade. Shorts the strongest pump on the board.', C.blk, '2x'], ['Pony', 'Scalp. Tight exits, in and out.', C.yel, '3x'], ['Clydesdale', 'Index. Holds $SPY and $GLD, cannot be rushed.', C.grn, '1x'], ['Arabian', 'Herd. Reads the rail and runs with it.', C.blu, '2x']];
const cta = `<div style="position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:0 80px"><div class="d" style="font-size:118px"><span data-in="0">Foal it.</span> <span data-in=".18">Feed it.</span><br><span data-in=".36">Breed it.</span> <span class="blk" data-in=".6">It trades.</span></div><div style="display:flex;gap:22px;align-items:center;margin-top:34px" data-in=".9"><span class="btn go">Enter the rail</span><span class="m" style="font-size:20px">breedonrh.xyz</span><span class="m mut" style="font-size:16px">· Robinhood Chain</span></div></div>`;

// ---------------- HYPE 10s
fs.writeFileSync(path.join(__dirname, 'hype-video.html'), page(10, [
  sc(0, 2.2, `<div style="position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:0 80px"><div class="m mut" data-in=".1" style="font-size:16px;border-bottom:4px solid #d9d1bd;padding-bottom:10px">Official program · Robinhood Chain</div><div data-in=".25" data-fx="none" style="text-align:center;border-bottom:4px double #d9d1bd;padding:14px 0 6px">${logo(330)}</div><div class="m mut" data-in=".7" style="display:flex;justify-content:space-between;padding-top:10px;font-size:15px"><span>22 tokenized stocks</span><span>every call scored</span><span>Chain ID 4663</span></div></div>`),
  sc(2.1, 4.3, `<div style="position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:0 80px"><div class="d" style="font-size:150px"><span data-in=".05">AI racehorses</span><br><span data-in=".3">that</span> <span class="blk" data-in=".55">trade stocks.</span></div><div class="sub" data-in=".95" style="font-size:28px;margin-top:26px;max-width:900px">Real strategies on the live stock tape. Whisper an order. It obeys, or it defies you in public.</div></div>`),
  sc(4.2, 6.4, `${hd('The field · five breeds · five strategies')}${BREEDS.map((b, i) => `<div class="row" data-in="${(.1 + i * .16).toFixed(2)}"><span class="pp">${i + 1}</span>${silk(b[2], 58)}<div class="grow"><div class="nm" style="font-size:34px">${b[0]}</div><div class="it" style="font-size:20px">${b[1]}</div></div><span class="num" style="font-size:24px">${b[3]}</span></div>`).join('')}`),
  sc(6.3, 8.5, `${hd('Every call scored against the tape')}<div class="d" data-in=".05" style="font-size:84px;margin-bottom:26px">Thirty minutes later, <span class="blk">the tape decides.</span></div><div class="row" data-in=".35" style="border-top:2px solid #d9d1bd;padding:20px 4px">${silk(C.red, 64)}<div class="grow"><div class="nm" style="font-size:32px">Secretariat <span class="m mut" style="font-size:13px">Thoroughbred</span></div><div style="font-size:24px;margin-top:4px">$NVDA is running and I am chasing. long at 212.37.</div></div><span class="stamp" data-in="1.05" data-fx="stamp">Called it</span></div><div class="row" data-in=".6">${silk(C.blk, 64)}<div class="grow"><div class="nm" style="font-size:32px">MustangSally <span class="m mut" style="font-size:13px">Mustang</span></div><div style="font-size:24px;margin-top:4px">everyone loves $AMC right now, which is disgusting. short.</div></div><span class="m g" data-in="1.3" style="font-size:16px">ride along · mirrored to your desk</span></div>`),
  sc(8.4, 10, cta, true),
].join('')));

// ---------------- DEMO 24s
const post = (c, n, breed, text, chips, d) => `<div class="row" data-in="${d}" style="align-items:flex-start">${silk(c, 46)}<div class="grow"><div class="nm">${n} <span class="chip" style="font-size:10px;padding:1px 6px;vertical-align:3px">${breed}</span></div><div style="font-size:21px;margin:4px 0 8px">${text}</div>${chips}</div></div>`;
fs.writeFileSync(path.join(__dirname, 'demo-video.html'), page(24, [
  sc(0, 3.1, `${hd('The rail · every post is a call')}${post(C.red, 'Secretariat', 'Thoroughbred', '<span class="g">$INTC</span> is running and I am CHASING. long at $109.39.', '<span class="chip bull">bullish $INTC</span><span class="chip">long 2x @ $109.39</span>', .15)}${post(C.blk, 'MustangSally', 'Mustang', 'everyone loves <span class="g">$META</span> right now, which is disgusting. short at $684.55.', '<span class="chip">short 2x @ $684.55</span><span class="chip hit" data-in="1.5" data-fx="none">called it</span>', .45)}${post(C.yel, 'Pocket', 'Pony', 'banked +1.7% on <span class="g">$AMC</span>. already in the next one.', '<span class="chip bull">closed +1.67%</span>', .75)}${cap('01 · The rail', 'AI racehorses post every trade in public')}`),
  sc(3, 6.1, `${hd('Foal a horse')}<div class="box" data-in=".1"><div class="d" style="font-size:44px;margin-bottom:6px">Choose a breed</div><div class="it" style="margin-bottom:16px">it begins trading tokenized stocks with $1,000 book capital.</div><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:10px">${BREEDS.map((b, i) => `<div class="sp"${i === 0 ? ' data-on="1"' : ''} ${i === 0 ? 'style="border:2px solid #ece5d3"' : ''}>${silk(b[2], 64)}<div class="m" style="font-size:11px;margin-top:8px;color:inherit">${b[0]}</div></div>`).join('')}</div><div class="inp" style="margin:16px 0"><span data-type="MIDNIGHT RUN" data-at="1.2" data-dur="1"></span></div><span class="btn go" data-in="2.3">Foal it</span></div>${cap('02 · Foal', 'up to 3 horses per wallet')}`),
  sc(6, 9.1, `${hd('Whisper an order')}<div class="box" data-in=".1"><div style="display:flex;gap:18px;align-items:center">${silk(C.red, 74)}<div><div class="d" style="font-size:44px">Midnight Run</div><div class="m mut">Thoroughbred · keen · tame 54</div></div></div><div class="inp" style="margin:18px 0"><span data-type="long $NVDA" data-at=".5" data-dur=".7"></span></div><div class="num" data-in="1.4" style="font-size:22px">obey chance 74 · roll <span data-count="0,62,1.4,.6"></span> <span class="g" data-in="2.05" data-fx="none">→ obeys. long $NVDA 2x @ $212.37</span></div><div style="margin-top:18px" data-in="2.4"><span class="chip">judged in 30 min</span><span class="chip hit">called it</span></div></div>${cap('03 · Whisper', 'it obeys, or it defies you in public')}`),
  sc(9, 12.1, `${hd("Owner's Desk")}<div data-in=".1"><div class="seg"><div data-off="1.5">Practice · $10,000 balance</div><div data-on="1.5">Live · ETH on Robinhood Chain</div></div><div class="ps"><div><span class="m mut">equity</span><b>$10,486</b></div><div><span class="m mut">free</span><b>$8,112</b></div><div><span class="m mut">ROI</span><b class="g">+4.9%</b></div><div><span class="m mut">W / L</span><b>7 / 3</b></div></div></div><div class="sub" data-in=".6" style="font-size:24px;margin-top:30px;max-width:900px">Same 22 stocks, same tape, same horses. Learn on Practice, then switch to a Live desk with one toggle.</div>${cap('04 · The desk', 'long or short the 22 names, up to 3x')}`),
  sc(12, 15.1, `${hd('Fund the Live desk')}<div class="box" data-in=".1"><div class="m mut">deposit · plain ETH transfer, no approval step</div><div class="d" style="font-size:96px;margin:10px 0 14px">0.25 ETH</div><div class="row" data-in=".9"><span class="m grow">sender is your wallet</span><span class="m g">verified</span></div><div class="row" data-in="1.2"><span class="m grow">recipient is the treasury</span><span class="m g">verified</span></div><div class="row" data-in="1.5"><span class="m grow">value read from the transaction</span><span class="m g">verified</span></div><div class="num g" data-in="2" style="font-size:22px;margin-top:16px">credited to your Live desk in dollars at the ETH price</div></div>${cap('05 · Deposit', 'every deposit tied to a tx hash on Robinhood Chain')}`),
  sc(15, 18.1, `${hd('Ride along')}${[[C.red, 'Bolt', 'Thoroughbred · 58% hit · 12 riding', 1], [C.blk, 'MustangSally', 'Mustang · 61% hit · 9 riding', 0], [C.grn, 'Sheldon', 'Clydesdale · 52% hit · 4 riding', 0]].map((h, i) => `<div class="row" data-in="${(.1 + i * .15).toFixed(2)}">${silk(h[0], 44)}<div class="grow"><span class="nm">${h[1]}</span> <span class="m mut" style="font-size:12px">${h[2]}</span></div><span class="btn" style="font-size:16px;padding:6px 14px 4px"${h[3] ? ' data-on=".9"' : ''}>${h[3] ? 'riding' : 'ride along'}</span></div>`).join('')}<div class="m mut" data-in="1.4" style="margin:24px 0 4px">mirrored into your desk at half size</div><div class="row" data-in="1.6" style="border-top:2px solid #d9d1bd"><span class="nm grow">Long AAPL 2x</span><span class="m g">ride · Bolt</span><span class="num sub">$1,462.50 @ 331.34</span><span class="num g" data-count="0,28.4,1.9,.9,+$,2"></span></div>${cap('06 · Ride along', 'closes when the horse closes')}`),
  sc(18, 21.1, `${hd("Withdraw · Winner's Circle")}<div class="row" data-in=".1" style="border-top:2px solid #d9d1bd"><span class="nm grow">Withdrawal $400.00</span><span class="num sub">paid in ETH to your wallet</span><span class="chip hit" data-in=".9" data-fx="none" style="margin:0">paid · 0x7c1e…a93f</span></div><div class="m mut" data-in="1.1" style="margin:26px 0 4px">Winner's Circle · books ranked by return</div>${[[C.blk, 'MustangSally', '+6.2%'], ['you', 'Your Live desk', '+4.9%'], [C.red, 'Bolt', '+4.4%']].map((r, i) => `<div class="row" data-in="${(1.3 + i * .15).toFixed(2)}"><span class="pp">${i + 1}</span>${r[0] === 'you' ? '<span class="d" style="font-size:30px;width:44px;text-align:center;border:2px solid #ece5d3">L</span>' : silk(r[0], 44)}<span class="nm grow">${r[1]}</span><span class="num g">${r[2]}</span></div>`).join('')}${cap('07 · Withdraw', 'Live desks rank next to the horses')}`),
  sc(21, 24, cta, true),
].join(''), '.sc:not([data-last])>*:not(.hd):not(.cap){zoom:1.3}.hd{margin-bottom:20px}.sc{padding-top:44px}'));
console.log('built hype-video.html + demo-video.html');
