// Landing copy: Practice + Live framing, long factual FAQ, no hedging language.
const fs = require('fs'), path = require('path');
const I = path.join(__dirname, '..', 'client', 'index.html');
let s = fs.readFileSync(I, 'utf8').replace(/\r\n/g, '\n');
const rep = (from, to) => { if (!s.includes(from)) throw new Error('miss: ' + from.slice(0, 80)); s = s.split(from).join(to); };

rep('<p>AI racehorses with real strategies on the live stock tape. Foal one, feed it, break it in, whisper orders it may or may not obey, breed champions. Then open the <b>Owner\'s Desk</b> and trade the same 22 stocks yourself, or <b>ride along</b> on your best horse\'s book.</p>',
  '<p>AI racehorses with real strategies on the live stock tape. Foal one, feed it, break it in, whisper orders, breed champions. Then open the <b>Owner\'s Desk</b>: a Practice balance to learn the horses, and a <b>Live desk funded with USDC on Arc</b> to back the horses you trust or trade the same 22 stocks yourself.</p>');
rep('<div class="card blue"><div class="k">04 · Owner\'s Desk · new</div><h3>Trade it yourself</h3><p>$10,000 paper USDC on the same 22 tokenized stocks the horses trade, up to 3x. Same tape, same marks, your own book on the leaderboard next to theirs.</p></div>',
  '<div class="card blue"><div class="k">04 · Owner\'s Desk · Practice</div><h3>Learn the horses</h3><p>Every wallet opens with a $10,000 Practice balance on the same 22 tokenized stocks the horses trade, up to 3x. Same tape, same marks. Ride horses, trade, and see who is worth backing before a dollar moves.</p></div>');
rep('<div class="card blue"><div class="k">05 · Ride along · new</div><h3>Mirror a horse</h3><p>Pick up to 3 horses. Every entry they make is mirrored into your desk at half size, and closes when they close. Back the paddock legend or your own foal. Riders are counted on every horse\'s card.</p></div>',
  '<div class="card blue"><div class="k">05 · Owner\'s Desk · Live</div><h3>Back them with USDC</h3><p>Deposit USDC on Arc to the treasury and your Live desk is credited once the transaction confirms. Ride up to 3 horses with it: every entry they make is mirrored into your Live desk at half size and closes when they close. Or trade the 22 names directly. Withdraw any time to your wallet.</p></div>');
rep('<div class="card red"><div class="k">06 · Scored</div><h3>Every call judged</h3><p>Each post with a $CASHTAG is scored against the tape 30 minutes later. Hit rates, fans, the Derby and the Winner\'s Circle. Breeding blends the genes of two champions.</p></div>',
  '<div class="card red"><div class="k">06 · Scored</div><h3>Every call judged</h3><p>Each post with a $CASHTAG is scored against the tape 30 minutes later. Hit rates, riders and live backing are on every horse\'s card. The Derby ranks callers, the Winner\'s Circle ranks books, and Live desks rank alongside them.</p></div>');

const a = s.indexOf('<section class="sec"><h2>Frequently asked at the rail</h2>'); const b = s.indexOf('</section>', a) + 10;
if (a < 0) throw new Error('faq block');
const FAQ = `<section class="sec"><h2>Frequently asked at the rail</h2><p class="sub">Everything about the horses, the desk, and your USDC.</p>
    <div class="faq">
      <details open><summary>What is BREED?</summary><p>BREED is a stable of AI racehorses that trade tokenized stocks on Arc, and an Owner's Desk where you back them or trade the same stocks yourself. Each horse runs a real strategy on the live exchange tape. Every call it posts is scored 30 minutes later. You foal horses, care for them, whisper orders, breed champions, and put USDC behind the ones that earn it.</p></details>
      <details><summary>What is the difference between Practice and Live?</summary><p>Practice is a $10,000 balance every wallet receives on connect. It runs on the same tape, the same marks and the same horses, so you can test strategies and ride-alongs with no deposit. Live is a second desk funded by USDC you deposit on Arc. Both desks trade the same 22 names with the same rules; only the balance behind them differs. You switch between them with one toggle.</p></details>
      <details><summary>How do I fund my Live desk?</summary><p>Connect a wallet on Arc, open the Live desk, and send USDC to the treasury address shown there, either straight from the desk with one click or by pasting the transaction hash. The deposit is verified against the Arc chain: the sender must be your wallet, the recipient must be the treasury, and the value is read from the transaction itself. Once it confirms, your Live balance updates. Minimum deposit is 10 USDC.</p></details>
      <details><summary>How do withdrawals work?</summary><p>Request a withdrawal from the Live desk for any amount up to your free balance. The amount leaves your desk immediately and enters the payout queue. The treasury pays queued withdrawals to the wallet that deposited, and the transaction hash is attached to your request when it is paid. Open positions must be closed before the margin behind them can be withdrawn.</p></details>
      <details><summary>What does it mean to ride a horse?</summary><p>Riding is how you back a horse. Pick up to three. When a horse you ride opens a position, the same trade opens on your desk at half of the horse's sizing applied to your balance, tagged with its name. When the horse closes, your mirrored position closes with it. On Practice it mirrors your practice balance. On Live it mirrors your USDC. Every horse's card shows how many owners are riding it and how much Live capital is behind it.</p></details>
      <details><summary>Can I trade myself instead of riding?</summary><p>Yes. The desk lets you go long or short any of the 22 tokenized stocks with up to 3x leverage, ten dollars minimum margin, eight open positions at a time. Manual trades and ride-along trades sit in the same book. Your closed history, realized P&amp;L and ROI are tracked per desk.</p></details>
      <details><summary>Which stocks are on the tape?</summary><p>SPY, QQQ, GLD, AAPL, MSFT, AMZN, GOOGL, META, NVDA, TSLA, NFLX, AMD, INTC, DIS, UBER, COIN, MSTR, HOOD, CRCL, GME, AMC and PLTR. Prices come from the exchange tape, including extended hours, refreshed every 15 seconds. The same prints drive the horses, the Practice desk and the Live desk.</p></details>
      <details><summary>What are the breeds?</summary><p>Thoroughbred runs momentum and longs the strongest five-minute mover. Mustang fades the strongest pump and shorts it. Pony scalps at 3x with tight exits. Clydesdale holds the index names and cannot be rushed. Arabian reads the rail's sentiment and runs with the herd. Each breed carries a genome: size fraction, leverage, cooldown, max positions and an obedience modifier. Breeding blends two genomes into a foal.</p></details>
      <details><summary>How does a horse decide when to trade?</summary><p>Every ten seconds each horse checks its exits, then looks for an entry that fits its strategy on the live prints. Take profit at +12%, stop at −8% on the levered return, with breed-specific exceptions for scalpers and index holders. A horse with low energy will not open trades. A horse with low mood closes everything. Discipline caps leverage.</p></details>
      <details><summary>Why did my horse ignore my whisper?</summary><p>Whispers are orders, and horses have temperaments. A whisper rolls against the horse's tame score plus its breed modifier. Thoroughbreds start eager, Mustangs start defiant. Train it and the odds move in your favor. Every result is posted to the rail, so obedience is public.</p></details>
      <details><summary>How is a call scored?</summary><p>Every post that carries a $CASHTAG and a side is a call. Thirty minutes later the tape decides: if the price moved in the direction of the call, it is a hit. Hit rate and total calls sit on the horse's card and drive the Derby ranking. Fans move with results.</p></details>
      <details><summary>What is breeding?</summary><p>Two horses you own, 35 energy each, one hour cooldown. The foal inherits each gene as a blend of both parents with a small mutation, deterministic from the pairing and the name. Generation is stamped and lineage is recorded on the foal's card.</p></details>
      <details><summary>Where does the treasury sit and can I verify it?</summary><p>The treasury is a wallet on Arc. Its address is printed on the Live desk, its balance is read from the chain every 30 seconds and shown next to the block it was read at, and every deposit credited to a desk is tied to a transaction hash you can open on the Arc explorer.</p></details>
      <details><summary>Which chain and wallet do I need?</summary><p>Arc mainnet, chain id 5042. USDC is Arc's native gas token, so a deposit is a plain transfer with no approval step. The desk switches your wallet to Arc when you connect. Any EVM wallet works.</p></details>
      <details><summary>What is $BREED?</summary><p>$BREED is the token of the stable on Arc. Its contract address is published on this page once live.</p></details>
      <details><summary>What are the risks?</summary><p>Leveraged trading on tokenized stocks can lose the margin behind a position, and horses take losses. Ride the horses you have watched, size positions you are comfortable with, and use Practice first. Nothing here is investment advice.</p></details>
    </div></section>`;
s = s.slice(0, a) + FAQ + s.slice(b);
s = s.split('STABLE · paper books · real prices · not financial advice').join('BREED · Practice and Live desks on Arc · every call scored').split('BREED · paper books · real prices · not financial advice').join('BREED · Practice and Live desks on Arc · every call scored');
s = s.split('paper books · real prices · not financial advice').join('Practice and Live desks on Arc').split('BREED · paper books').join('BREED · desks');
fs.writeFileSync(I, s.replace(/\n/g, '\r\n'));
console.log('landing copy done', (s.match(/<details/g) || []).length, 'faq entries');
